// Keyboard key scan codes
// These are taken from the USB keyboard usage page documentation
// http://www.usb.org/developers/hidpage/Hut1_12v2.pdf
//
// The codes here are from usage page 0x07 (keyboard)
// Some other scan codes might find their way in here as real world 
// dictates
//
// Scan codes are the raw values that come from the USB keyboard, before the OS does any
// modification of them to create "virtual keys".  They are useful when you are interested 
// in which actual keys are being pressed on the keyboard, regardless of how they are 
// labeled or mapped.

typedef enum {
	KSC_SCANCODE_NONE = 0x0000,

	KSC_SCANCODE_A = 0x04,
	KSC_SCANCODE_B = 0x05,
	KSC_SCANCODE_C = 0x06,
	KSC_SCANCODE_D = 0x07,
	KSC_SCANCODE_E = 0x08,
	KSC_SCANCODE_F = 0x09,
	KSC_SCANCODE_G = 0x0A,
	KSC_SCANCODE_H = 0x0B,
	KSC_SCANCODE_I = 0x0C,
	KSC_SCANCODE_J = 0x0D,
	KSC_SCANCODE_K = 0x0E,
	KSC_SCANCODE_L = 0x0F,
	KSC_SCANCODE_M = 0x10,
	KSC_SCANCODE_N = 0x11,
	KSC_SCANCODE_O = 0x12,
	KSC_SCANCODE_P = 0x13,
	KSC_SCANCODE_Q = 0x14,
	KSC_SCANCODE_R = 0x15,
	KSC_SCANCODE_S = 0x16,
	KSC_SCANCODE_T = 0x17,
	KSC_SCANCODE_U = 0x18,
	KSC_SCANCODE_V = 0x19,
	KSC_SCANCODE_W = 0x1A,
	KSC_SCANCODE_X = 0x1B,
	KSC_SCANCODE_Y = 0x1C,
	KSC_SCANCODE_Z = 0x1D,

	// upper row of numeric keys
	KSC_SCANCODE_1 = 0x1E,
	KSC_SCANCODE_2 = 0x1F,
	KSC_SCANCODE_3 = 0x20,
	KSC_SCANCODE_4 = 0x21,
	KSC_SCANCODE_5 = 0x22,
	KSC_SCANCODE_6 = 0x23,
	KSC_SCANCODE_7 = 0x24,
	KSC_SCANCODE_8 = 0x25,
	KSC_SCANCODE_9 = 0x26,
	KSC_SCANCODE_0 = 0x27,

	KSC_SCANCODE_RETURN			= 0x28,
	KSC_SCANCODE_ESCAPE			= 0x29,
	KSC_SCANCODE_BACKSPACE		= 0x2A,
	KSC_SCANCODE_TAB			= 0x2B,
	KSC_SCANCODE_SPACE			= 0x2C,
	KSC_SCANCODE_MINUS			= 0x2D,
	KSC_SCANCODE_EQUAL			= 0x2E,
	KSC_SCANCODE_LEFTBRACKET	= 0x2F,
	KSC_SCANCODE_RIGHTBRACKET	= 0x30,
	KSC_SCANCODE_BACKSLASH		= 0x31,

	KSC_SCANCODE_NONUSHASH		= 0x32,

	KSC_SCANCODE_SEMICOLON		= 0x33,
	KSC_SCANCODE_APOSTROPHE		= 0x34,
	KSC_SCANCODE_GRAVE			= 0x35,	// And '~'
	KSC_SCANCODE_COMMA			= 0x36,
	KSC_SCANCODE_PERIOD			= 0x37,
	KSC_SCANCODE_SLASH			= 0x38,

	KSC_SCANCODE_CAPSLOCK		= 0x39,

	KSC_SCANCODE_F1				= 0x3A,
	KSC_SCANCODE_F2				= 0x3B,
	KSC_SCANCODE_F3				= 0x3C,
	KSC_SCANCODE_F4				= 0x3D,
	KSC_SCANCODE_F5				= 0x3E,
	KSC_SCANCODE_F6				= 0x3F,
	KSC_SCANCODE_F7				= 0x40,
	KSC_SCANCODE_F8				= 0x41,
	KSC_SCANCODE_F9				= 0x42,
	KSC_SCANCODE_F10			= 0x43,
	KSC_SCANCODE_F11			= 0x44,
	KSC_SCANCODE_F12			= 0x45,

	KSC_SCANCODE_PRINTSCREEN	= 0x46,
	KSC_SCANCODE_SCROLLLOCK		= 0x47,
	KSC_SCANCODE_PAUSE			= 0x48,

	KSC_SCANCODE_INSERT			= 0x49,
	KSC_SCANCODE_HOME			= 0x4A,
	KSC_SCANCODE_PAGEUP			= 0x4B,
	KSC_SCANCODE_DELETE			= 0x4C,
	KSC_SCANCODE_				= 0x4D,
	KSC_SCANCODE_				= 0x4E,

	KSC_SCANCODE_RIGHT			= 0x4F,
	KSC_SCANCODE_LEFT			= 0x50,
	KSC_SCANCODE_DOWN			= 0x51,
	KSC_SCANCODE_UP				= 0x52,

	KSC_SCANCODE_NUMLOCKCLEAR	= 0x53,

	// KEYPAD
	KSC_SCANCODE_KP_DIVIDE = 0x54,
	KSC_SCANCODE_KP_MULTIPLY = 0x55,
	KSC_SCANCODE_KP_MINUS = 0x56,
	KSC_SCANCODE_KP_PLUS = 0x57,
	KSC_SCANCODE_KP_ENTER = 0x58,
	KSC_SCANCODE_KP_1 = 0x59,
	KSC_SCANCODE_KP_2 = 0x5A,
	KSC_SCANCODE_KP_3 = 0x5B,
	KSC_SCANCODE_KP_4 = 0x5C,
	KSC_SCANCODE_KP_5 = 0x5D,
	KSC_SCANCODE_KP_6 = 0x5E,
	KSC_SCANCODE_KP_7 = 0x5F,
	KSC_SCANCODE_KP_8 = 0x60,
	KSC_SCANCODE_KP_9 = 0x61,
	KSC_SCANCODE_KP_0 = 0x62,
	KSC_SCANCODE_KP_PERIOD = 0x63,

	KSC_SCANCODE_NONUSBACKSLASH = 0x64,

	KSC_SCANCODE_APPLICATION = 0x65,	// Windows contextual menu
	KSC_SCANCODE_POWER = 0x66,

	KSC_SCANCODE_KP_EQUALS = 0x67,

	// MORE FUNCTION KEYS
	KSC_SCANCODE_13 = 0x68,
	KSC_SCANCODE_14 = 0x69, 
	KSC_SCANCODE_15 = 0x6A,
	KSC_SCANCODE_16 = 0x6B,
	KSC_SCANCODE_17 = 0x6C,
	KSC_SCANCODE_18 = 0x6D,
	KSC_SCANCODE_19 = 0x6E,
	KSC_SCANCODE_20 = 0x6F,
	KSC_SCANCODE_21 = 0x70,
	KSC_SCANCODE_22 = 0x71,
	KSC_SCANCODE_23 = 0x72,
	KSC_SCANCODE_24 = 0x73,

	KSC_SCANCODE_EXECUTE = 0x74,
	KSC_SCANCODE_HELP = 0x75,
	KSC_SCANCODE_MENU = 0x76,
	KSC_SCANCODE_SELECT = 0x77,
	KSC_SCANCODE_STOP = 0x78,
	KSC_SCANCODE_AGAIN = 0x79,
	KSC_SCANCODE_UNDO = 0x7A,
	KSC_SCANCODE_CUT = 0x7B,
	KSC_SCANCODE_COPY = 0x7C,
	KSC_SCANCODE_PASTE = 0x7D,
	KSC_SCANCODE_FIND = 0x7E,
	KSC_SCANCODE_MUTE = 0x7F,
	KSC_SCANCODE_VOLUMEUP = 0x80,
	KSC_SCANCODE_VOLUMEDOWN = 0x81,

	// PROBABLY NOT USED MUCH THESE DAYS
	KSC_SCANCODE_LOCKINGCAPSLOCK = 0x82,
	KSC_SCANCODE_LOCKINGNUMLOCK = 0x83,
	KSC_SCANCODE_LOCKINGSCROLLLOCK = 0x84,


	KSC_SCANCODE_KP_COMMA = 0x85,
	KSC_SCANCODE_KP_EQUALSAS400 = 0x86,


	KSC_SCANCODE_INTERNATIONAL1 = 0x87,
	KSC_SCANCODE_INTERNATIONAL2 = 0x88,
	KSC_SCANCODE_INTERNATIONAL3 = 0x89,
	KSC_SCANCODE_INTERNATIONAL4 = 0x8A,
	KSC_SCANCODE_INTERNATIONAL5 = 0x8B,
	KSC_SCANCODE_INTERNATIONAL6 = 0x8C,
	KSC_SCANCODE_INTERNATIONAL7 = 0x8D,
	KSC_SCANCODE_INTERNATIONAL8 = 0x8E,
	KSC_SCANCODE_INTERNATIONAL9 = 0x8F,

	KSC_SCANCODE_LANG1 = 0x90,
	KSC_SCANCODE_LANG2 = 0x91,
	KSC_SCANCODE_LANG3 = 0x92,
	KSC_SCANCODE_LANG4 = 0x93,
	KSC_SCANCODE_LANG5 = 0x94,
	KSC_SCANCODE_LANG6 = 0x95,	// RESERVED FOR LANGUAGE SPECIFIC FUNCTION
	KSC_SCANCODE_LANG7 = 0x96,	// RESERVED FOR LANGUAGE SPECIFIC FUNCTION
	KSC_SCANCODE_LANG8 = 0x97,	// RESERVED FOR LANGUAGE SPECIFIC FUNCTION
	KSC_SCANCODE_LANG9 = 0x98,	// RESERVED FOR LANGUAGE SPECIFIC FUNCTION

	KSC_SCANCODE_ALTERASE = 0x99,
	KSC_SCANCODE_SYSREQ = 0x9A,
	KSC_SCANCODE_CANCEL = 0x9B,
	KSC_SCANCODE_CLEAR = 0x9C,
	KSC_SCANCODE_PRIOR = 0x9D,
	KSC_SCANCODE_RETURN2 = 0x9E,
	KSC_SCANCODE_SEPARATOR = 0x9F,
	KSC_SCANCODE_OUT = 0xA0,
	KSC_SCANCODE_OPER = 0xA1,
	KSC_SCANCODE_CLEARAGAIN = 0xA2,
	KSC_SCANCODE_CRSEL = 0xA3,
	KSC_SCANCODE_EXSEL = 0xA4,

	// A5 - AF  RESERVED


	KSC_SCANCODE_KP_00 = 0xB0,
	KSC_SCANCODE_KP_000 = 0xB1,
	KSC_SCANCODE_THOUSANDSSEPARATOR = 0xB2,
	KSC_SCANCODE_DECIMALSEPARATOR = 0xB3,
	KSC_SCANCODE_CURRENCYUNIT = 0xB4,
	KSC_SCANCODE_CURRENCYSUBUNIT = 0xB5,
	KSC_SCANCODE_KP_LEFTPAREN = 0xB6,
	KSC_SCANCODE_KP_RIGHTPAREN = 0xB7,
	KSC_SCANCODE_KP_LEFTBRACE = 0xB8,
	KSC_SCANCODE_KP_RIGHTBRACE = 0xB9,
	KSC_SCANCODE_KP_TAB = 0xBA,
	KSC_SCANCODE_KP_BACKSPACE = 0xBB,
	KSC_SCANCODE_KP_A = 0xBC,
	KSC_SCANCODE_KP_B = 0xBD,
	KSC_SCANCODE_KP_C = 0xBE,
	KSC_SCANCODE_KP_D = 0xBF,
	KSC_SCANCODE_KP_E = 0xC0,
	KSC_SCANCODE_KP_F = 0xC1,
	KSC_SCANCODE_KP_XOR = 0xC2,
	KSC_SCANCODE_KP_POWER = 0xC3,
	KSC_SCANCODE_KP_PERCENT = 0xC4,
	KSC_SCANCODE_KP_LESS = 0xC5,
	KSC_SCANCODE_KP_GREATER = 0xC6,
	KSC_SCANCODE_KP_AMPERSAND = 0xC7,
	KSC_SCANCODE_KP_DBLAMPERSAND = 0xC8,
	KSC_SCANCODE_KP_VERTICALBAR = 0xC9,
	KSC_SCANCODE_KP_DBLVERTICALBAR = 0xCA,
	KSC_SCANCODE_KP_COLON = 0xCB,
	KSC_SCANCODE_KP_HASH = 0xCC,
	KSC_SCANCODE_KP_SPACE = 0xCD,
	KSC_SCANCODE_KP_AT = 0xCE,
	KSC_SCANCODE_KP_EXCLAM = 0xCF,
	KSC_SCANCODE_KP_MEMSTORE = 0xD0,
	KSC_SCANCODE_KP_MEMRECALL = 0xD1,
	KSC_SCANCODE_KP_MEMCLEAR = 0xD2,
	KSC_SCANCODE_KP_MEMADD = 0xD3,
	KSC_SCANCODE_KP_MEMSUBTRACT = 0xD4,
	KSC_SCANCODE_KP_MEMMULTIPLY = 0xD5,
	KSC_SCANCODE_KP_MEMDIVIDE = 0xD6,
	KSC_SCANCODE_KP_PLUSMINUS = 0xD7,
	KSC_SCANCODE_KP_CLEAR = 0xD8,
	KSC_SCANCODE_KP_CLEARENTRY = 0xD9,
	KSC_SCANCODE_KP_BINARY = 0xDA,
	KSC_SCANCODE_KP_OCTAL = 0xDB,
	KSC_SCANCODE_KP_DECIMAL = 0xDC,
	KSC_SCANCODE_KP_HEXADECIMAL = 0xDD,

	// DE - DF   RESERVED

	KSC_SCANCODE_LCTRL			= 0xE0,
	KSC_SCANCODE_LSHIFT			= 0xE1,
	KSC_SCANCODE_LALT			= 0xE2,
	KSC_SCANCODE_LGUI			= 0xE3,		// THE WINDOWS KEY
	KSC_SCANCODE_RCTRL			= 0xE4,
	KSC_SCANCODE_RSHIFT			= 0xE5,
	KSC_SCANCODE_RALT			= 0xE6,
	KSC_SCANCODE_RGUI			= 0xE7,

} Keyboard_Scancode;